version: '3'
services:

    tech_blog:
        container_name: tech_blog
        tty: true
        build: .
        ports:
            - 3000:3000
        volumes:
            - ./app:/app
        command: npm run dev
